; A more realistic MPPT control function

; TODO increase step authority when it gets stuck ??
; TODO (cause of problems - low voltage resolution)

; TODO don't ignore OCP Cxxx


; previous values
(= pp 0)
(= pv 0)
;(= pr 0)

(= d 0) ; duty
(= ti 0) ; time

; configuration parameters (uppercase vars) are in 30-control-conf.lisp

(= pump (fn ()
  (out "PUMP"
    (if
      (pwrg "last5m") (if
          (not t0) t  ; t0 is nil - broken sensor
          (and
            (not (out "PUMP"))  ; do not switch relay off if temperature falls
            (< t0 PS)
          ) nil
          t
        )
      nil  ; turbine in not generating power
    )
  )
))

(= swen (fn ()
  (pwrs "sw_enable"
    (if
      (not t0) nil  ; always off if the temperature sensor doesn't work
      (if
        (pwrg "sw_enable") (< t0 T0M)  ; enabled - check MAX
        (< t0 T0S)  ; disabled - check start
      )
    )
  )
))

(= mppt (fn ()
  (let v (pwrg "voltage"))
  (let i (pwrg "current"))
  (let r (pwrg "RPM"))
  (ctrls "contactor" (< RLC r))
  (let p (* v i)) ; power delivered to the load
  ;(let p
  ;  (+ (* v i) (* J r (/ (- r pr) Ts))))  ; power generated by the turbine

  (let s ; step direction
    (if (is (< pp p) (< pv v)) -1 1))

  ; don't get stuck at 0
  ;(if (is d 0) (= s 1))
  ; don't get stuck at 255
  ;(if (is d 255) (= s -1))

  ; save previous values
  (= pp p)
  (= pv v)
  ;(= pr r)

  ; RPM limits
  (= d
    (if
      (< r RL) 0
      (< RH r) 255
      ; our control loop does not run extremely often,
      ; so better give step (s) more authority
      (+ d (* s SA))
    )
  )
  ; power mode
  (= d
    (if
      (is (pwrg "mode") pwr_const_duty) d
      0
    )
  )
  ; duty limits
  (= d (lim d 0 255))
  (pwrs "duty" d)
))

(= ctrl (fn ()
  ; ctrl is called each time a new state object is received.
  ; If everything is working correctly, that should be every 0.5 seconds.
  (= ti (+ ti 0.5))

  (= t0 (ds18 0))
  (swen)
  (pump)

  (if (<= Ts ti)
    (do
      (= ti (- ti Ts)) ; prevent loss of precision in float numbers
      (mppt)
      ))
))
