;;; HCS / P&O MPPT: prev duty cycle variant

;; parameters
(= SA 3) ; step authority
(= Ts 12) ; MPPT sampling period in seconds

;; previous values
(= pp 0) ; previous power
(= ps 0) ; previous step

; d (duty) is a global variable defined in 31-control-MPPT

(= mppt (fn ()
  (let v (pwrg "voltage"))
  (let i (pwrg "current"))
  (let p (* v i)) ; power delivered to the load
  ;(let p
  ;  (+ (* v i) (* J r (/ (- r pr) Ts))))  ; power generated by the turbine

  (let s
    (if (is (< p pp) (< ps 0)) 1 -1))

  (= s (if
    (is d 0) 2 ; don't get stuck at 0
    (is d 255) -1 ; don't get stuck at 255
    s))

  ; save previous values
  (= pp p)
  (= ps s)
  (* s SA)))  ; return step
