# vim: tabstop=2 softtabstop=2 shiftwidth=2 expandtab

recorder:
  exclude:
    entities:
      - sensor.vetrnik_zpravy_vykonove_elektroniky


mqtt:
  sensor:
    - name: Vetrnik RPM
      unit_of_measurement: RPM
      state_topic: vetrnik/tele/power_board/RPM
      availability_topic: vetrnik/tele/availability

    - name: Vetrnik napeti
      unit_of_measurement: V
      device_class: voltage
      state_topic: vetrnik/tele/power_board/voltage
      availability_topic: vetrnik/tele/availability

    - name: Vetrnik proud
      unit_of_measurement: A
      device_class: current
      state_topic: vetrnik/tele/power_board/current
      availability_topic: vetrnik/tele/availability

    - name: Vetrnik vykon
      unit_of_measurement: W
      device_class: power
      state_topic: vetrnik/tele/power_board/power
      availability_topic: vetrnik/tele/availability

    - name: Vetrnik teplota chladice s tranzistory
      unit_of_measurement: "°C"
      device_class: temperature
      state_topic: vetrnik/tele/power_board/temperature/heatsink
      availability_topic: vetrnik/tele/availability

    - name: Vetrnik teplota chladice s usmernovacem
      unit_of_measurement: "°C"
      device_class: temperature
      state_topic: vetrnik/tele/power_board/temperature/rectifier
      availability_topic: vetrnik/tele/availability

    - name: Vetrnik teplota vody
      unit_of_measurement: "°C"
      device_class: temperature
      state_topic: vetrnik/tele/temperature/voda
      availability_topic: vetrnik/tele/availability

    - name: Vetrnik pocet chyb
      unit_of_measurement: errors
      state_topic: vetrnik/tele/power_board/error_count
      availability_topic: vetrnik/tele/availability

    - name: Vetrnik strida
      unit_of_measurement: "%"
      value_template: '{{ ((value|int(0))*100/255)|round(1)  }}'
      state_topic: vetrnik/tele/power_board/duty
      availability_topic: vetrnik/tele/availability

    - name: Vetrnik maximalni strida
      unit_of_measurement: "%"
      value_template: '{{ ((value|int(0))*100/255)|round(1) }}'
      state_topic: vetrnik/tele/power_board/OCP_max_duty
      availability_topic: vetrnik/tele/availability

    - name: Vetrnik energie
      unit_of_measurement: kWh
      state_topic: vetrnik/tele/stats/energy
      state_class: total_increasing
      device_class: energy
      availability_topic: vetrnik/tele/availability

    - name: Vetrnik rezim vykonove elektroniky
      state_topic: vetrnik/tele/power_board/mode
      value_template: >-
        {%
          set modes = {
            0: "shorted",
            1: "stopping",
            2: "const_duty",
          }
        %}
        {{ modes[value | int(0)] }}
      availability_topic: vetrnik/tele/availability

    - name: Vetrnik zpravy vykonove elektroniky
      state_topic: vetrnik/tele/raw/errors
      availability_topic: vetrnik/tele/availability


  binary_sensor:
    - name: Vetrnik muze topit
      state_topic: vetrnik/tele/power_board/enabled
      device_class: running
      payload_on: "1"
      payload_off: "0"
      availability_topic: vetrnik/tele/availability

    - name: Vetrnik chladi
      #device_class: heat  # it's not "too hot", it's just that the fan is running
      device_class: running
      state_topic: vetrnik/tele/power_board/fan
      payload_on: "1"
      payload_off: "0"
      availability_topic: vetrnik/tele/availability

    - name: Vetrnik nouzovy rezim
      state_topic: vetrnik/tele/power_board/emergency
      device_class: problem
      payload_on: "1"
      payload_off: "0"
      availability_topic: vetrnik/tele/availability

    - name: Vetrnik poslednich 5 minut
      device_class: power
      state_topic: vetrnik/tele/power_board/last5m
      payload_on: "1"
      payload_off: "0"
      availability_topic: vetrnik/tele/availability

    - name: Vetrnik vykonova elektronika komunikuje
      device_class: connectivity
      state_topic: vetrnik/tele/power_board/valid
      payload_on: "1"
      payload_off: "0"
      availability_topic: vetrnik/tele/availability

  select:
    - name: Vetrnik strategie rizeni
      state_topic: vetrnik/tele/control/strategy
      command_topic: vetrnik/cmnd/control/strategy
      options:
        - control_shorted
        - control_manual
        - control_MQTT
        - control_lisp
      availability_topic: vetrnik/tele/availability

  switch:
    - name: Vetrnik cerpadlo
      icon: "mdi:pump"
      state_topic: vetrnik/tele/pump
      command_topic: vetrnik/cmnd/pump
      payload_on: "1"
      payload_off: "0"
      availability_topic: vetrnik/tele/availability

    - name: Vetrnik podsviceni displeje
      icon: "mdi:brightness-5"
      state_topic: vetrnik/tele/display/backlight
      command_topic: vetrnik/cmnd/display/backlight
      payload_on: "1"
      payload_off: "0"
      availability_topic: vetrnik/tele/availability

  button:
    - name: Vetrnik START
      command_topic: vetrnik/cmnd/lisp
      payload_press: "(btn1_long)"
      icon: "mdi:play"
      availability_topic: vetrnik/tele/availability

    - name: Vetrnik STOP
      command_topic: vetrnik/cmnd/lisp
      payload_press: "(btn1_short)"
      icon: "mdi:stop"
      availability_topic: vetrnik/tele/availability

    - name: Vetrnik smazat chyby vykonove elektroniky
      command_topic: vetrnik/cmnd/power_board/command
      payload_press: "clear_errors"
      availability_topic: vetrnik/tele/availability

    - name: Vetrnik reset vykonove elektroniky
      command_topic: vetrnik/cmnd/power_board/command
      payload_press: "reset"
      icon: "mdi:restart"
      availability_topic: vetrnik/tele/availability


automation:
  - alias: Vetrnik notifikace
    mode: queued
    trigger:
      - platform: numeric_state
        entity_id: sensor.vetrnik_pocet_chyb
        above: 0
        id: Chyba vykonove elektroniky
      - platform: state
        entity_id: sensor.vetrnik_pocet_chyb
        to: unavailable
        for:
          minutes: 2
        id: MQTT nekomunikuje
      - platform: state
        entity_id: binary_sensor.vetrnik_vykonova_elektronika_komunikuje
        to: "off"
        id: Vykonova elektronika nekomunikuje
      - platform: state
        entity_id: select.vetrnik_strategie_rizeni
        not_to:
          - unavailable
          - unknown
        for:
          minutes: 2
        id: Zmena strategie rizeni
      - platform: state
        entity_id: binary_sensor.vetrnik_nouzovy_rezim
        to: "on"
        id: Nouzovy rezim
    condition: []
    action:
      - service: notify.email_vetrnik
        data:
          title: "[vetrnik] {{ trigger.id }}"
          message: |
            {% for e in [
                'sensor.vetrnik_pocet_chyb',
                'sensor.vetrnik_zpravy_vykonove_elektroniky',
                'binary_sensor.vetrnik_vykonova_elektronika_komunikuje',
                'select.vetrnik_strategie_rizeni',
                'binary_sensor.vetrnik_nouzovy_rezim',
                ] -%}

                {% set unit = state_attr(e, 'unit_of_measurement') -%}

                {{ state_attr(e, 'friendly_name') }}:
                {{ states(e) }}{{ ' '+unit if unit is not none }}
                (last changed {{ states[e.split('.')[0]][e.split('.')[1]].last_changed | as_local }})
            {% endfor %}
